apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: voting-preprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: REPLACE_WITH_ACR/worker:latest
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_TOPIC
            - name: KAFKA_GROUP
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_GROUP
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
